services:
  - type: web
    name: budbud-hindi-fp-school
    runtime: static
    buildCommand: "echo No build step required for static site"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
